EbookPlatform/Areas/Admin/Controllers/TranslatorsController.cs
using Microsoft.AspNetCore.Mvc;

namespace EbookPlatform.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class TranslatorsController : Controller
    {
        private readonly ILogger<TranslatorsController> _logger;
        private MyEbookPlatformContext _context;
        public TranslatorsController(ILogger<TranslatorsController> logger, MyEbookPlatformContext context)
        {
            _logger = logger;
            _context = context;
        }


        public IActionResult Index()
        {
            var translators = _context.translators.Where(c => c.isDeleted == false).ToList();
            return View(translators);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Translator translator)
        {
            if (!ModelState.IsValid)
            {
                return View(translator);

            }
            if (translatorDoesExist(translator.translatorFullName))
            {
                ModelState.AddModelError("translatorFullName", "این نویسنده تکراری است!");
                return View(translator);
            }

            _context.translators.Add(translator);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var translator = _context.translators.Find(id);
            translator.isDeleted = true;
            _context.translators.Update(translator);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            Translator translator = _context.translators.Find(id);

            if (translator == null)
            {
                Response.StatusCode = 404;
                return View("UserNotFound");
            }

            return View(translator);

        }

        [HttpPost]
        public IActionResult Edit(int id, Translator translator)
        {
            translator.translatorID = id;
            var translatorFound = _context.translators.Find(id);
            translatorFound.translatorFullName = translator.translatorFullName;
            translatorFound.description = translator.description;

            _context.SaveChanges();


            return RedirectToAction(nameof(Index));
        }


        public bool translatorDoesExist(string fullName)
        {
            if (_context.translators.Where(o => o.translatorFullName == fullName).Count() > 0)
            {
                return true;
            }
            else
                return false;
        }
    }
}

EbookPlatform/Areas/Admin/Views/Translators/Create.cshtml
@model EbookPlatform.Translator

@{
    ViewData["Title"] = "AddTranslator";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 mt-4 p-3">
    <div class="card-box">



        <form method="post" asp-area="Admin" asp-controller="Translators" asp-action="Create" style="margin-top:5%;">
            <div class="form-group">
                <label asp-for="translatorFullName"></label>
                <input asp-for="translatorFullName" type="text" parsley-trigger="change" class="form-control" data-parsley-id="6">
                <span asp-validation-for="translatorFullName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="description"></label>
                <input asp-for="description" type="text" class="form-control">
                <span asp-validation-for="description" class="text-danger"></span>
            </div>

            <div class="form-group text-right m-b-0">
                <button class="btn btn-primary waves-effect waves-light" type="submit">
                    ثبت اطلاعات
                </button>
                <a asp-action="Index" class="btn btn-default waves-effect waves-light m-l-5">
                    لغو
                </a>
            </div>

        </form>
    </div>
</div>

EbookPlatform/Areas/Admin/Views/Translators/Edit.cshtml
@model EbookPlatform.Translator

@{
    ViewData["Title"] = "EditTranslator";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 mt-4 p-3">
    <div class="card-box">



        <form method="post" asp-area="Admin" asp-controller="Translators" asp-action="Edit" style="margin-top:5%;">
            <div class="form-group">
                <label>نام مترجم</label>
                <input type="text" class="form-control" name="translatorFullName" value="@Model.translatorFullName">
                <span class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>توضیحات</label>
                <input type="text" class="form-control" name="description" value="@Model.description">
                <span class="text-danger"></span>
            </div>

            <div class="form-group text-right m-b-0">
                <button class="btn btn-primary waves-effect waves-light" type="submit">
                    ثبت اطلاعات
                </button>
                <a asp-action="Index" class="btn btn-default waves-effect waves-light m-l-5">
                    لغو
                </a>
            </div>

        </form>
    </div>
</div>

EbookPlatform/Areas/Admin/Views/Translators/Index.cshtml
@model IEnumerable<EbookPlatform.Translator>

@{
    ViewData["Title"] = "Translators";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="content">
    <div class="container">


        <div class="row">

            <div class="col-sm-12">
                <div class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="m-b-30">
                                    <a asp-area="Admin" asp-controller="Translators" asp-action="Create"><button class="btn btn-primary waves-effect waves-light">افزودن <i class="fa fa-plus"></i></button></a>

                                </div>
                            </div>
                        </div>

                        <div class="editable-responsive">
                            <table class="table table-striped" id="datatable-editable">
                                <thead>
                                    <tr>
                                        <th>ایدی</th>
                                        <th>نام مترجم</th>
                                        <th>توضیحات</th>
                                        <th>فعالیت</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="gradeX">
                                            <td>@item.translatorID</td>
                                            <td>
                                                @item.translatorFullName
                                            </td>
                                            <td>@item.description</td>
                                            <td class="actions">
                                                <a href="#" class="hidden on-editing save-row"><i class="fa fa-save"></i></a>
                                                <a href="#" class="hidden on-editing cancel-row"><i class="fa fa-times"></i></a>
                                                <a href="/Admin/Translators/Edit/@item.translatorID" class="on-default edit-row"><i class="fa fa-pencil"></i></a>
                                                <a href="/Admin/Translators/Delete/@item.translatorID" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
                                            </td>
                                        </tr>
                                    }




                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end: panel body -->

                </div> <!-- end panel -->
            </div>














        </div>
        <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->