EbookPlatform/Areas/Admin/Controllers/PublishersController.cs
using Microsoft.AspNetCore.Mvc;

namespace EbookPlatform.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PublishersController : Controller
    {
        private readonly ILogger<PublishersController> _logger;
        private MyEbookPlatformContext _context;
        public PublishersController(ILogger<PublishersController> logger, MyEbookPlatformContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            var publishers = _context.publishers.Where(c => c.isDeleted == false).ToList();
            return View(publishers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);

            }
            if (publisherDoesExist(publisher.publisherFullName))
            {
                ModelState.AddModelError("publisherFullName", "این نویسنده تکراری است!");
                return View(publisher);
            }

            _context.publishers.Add(publisher);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var publisher = _context.publishers.Find(id);
            publisher.isDeleted = true;
            _context.publishers.Update(publisher);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Edit(int id)
        {
            Publisher publisher = _context.publishers.Find(id);

            if (publisher == null)
            {
                Response.StatusCode = 404;
                return View("UserNotFound");
            }

            return View(publisher);

        }


        [HttpPost]
        public IActionResult Edit(int id, Publisher publisher)
        {
            publisher.publisherID = id;
            var publisherFound = _context.publishers.Find(id);
            publisherFound.publisherFullName = publisher.publisherFullName;
            publisherFound.description = publisher.description;

            _context.SaveChanges();


            return RedirectToAction(nameof(Index));
        }

        public bool publisherDoesExist(string fullName)
        {
            if (_context.publishers.Where(o => o.publisherFullName == fullName).Count() > 0)
            {
                return true;
            }
            else
                return false;
        }
    }
}

EbookPlatform/Areas/Admin/Views/Publishers/Create.cshtml
@model EbookPlatform.Publisher

@{
    ViewData["Title"] = "AddPublisher";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 mt-4 p-3">
    <div class="card-box">



        <form method="post" asp-area="Admin" asp-controller="Publishers" asp-action="Create" style="margin-top:5%;">
            <div class="form-group">
                <label asp-for="publisherFullName" for=""></label>
                <input asp-for="publisherFullName" type="text" parsley-trigger="change" placeholder=" " class="form-control" id="emailAddress" data-parsley-id="6">
                <span asp-validation-for="publisherFullName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="description"></label>
                <input type="text" class="form-control" asp-for="description">
                <span class="text-danger" asp-validation-for="description"></span>
            </div>

            <div class="form-group text-right m-b-0">
                <button class="btn btn-primary waves-effect waves-light" type="submit">
                    ثبت اطلاعات
                </button>
                <a asp-action="Index" class="btn btn-default waves-effect waves-light m-l-5">
                    لغو
                </a>
            </div>

        </form>
    </div>
</div>

EbookPlatform/Areas/Admin/Views/Publishers/Edit.cshtml
@model EbookPlatform.Publisher

@{
    ViewData["Title"] = "EditPublisher";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 mt-4 p-3">
    <div class="card-box">



        <form method="post" asp-area="Admin" asp-controller="Publishers" asp-action="Edit" style="margin-top:5%;">
            <div class="form-group">
                <label>نام ناشر</label>
                <input type="text" class="form-control" name="publisherFullName" value="@Model.publisherFullName">
                <span class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>توضیحات</label>
                <input type="text" class="form-control" name="description" value="@Model.description">
                <span class="text-danger"></span>
            </div>

            <div class="form-group text-right m-b-0">
                <button class="btn btn-primary waves-effect waves-light" type="submit">
                    ثبت اطلاعات
                </button>
                <a asp-action="Index" class="btn btn-default waves-effect waves-light m-l-5">
                    لغو
                </a>
            </div>

        </form>
    </div>
</div>

EbookPlatform/Areas/Admin/Views/Publishers/Index.cshtml
@model IEnumerable<EbookPlatform.Publisher>

@{
    ViewData["Title"] = "publishers";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="content">
    <div class="container">


        <div class="row">

            <div class="col-sm-12">
                <div class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="m-b-30">
                                    <a asp-area="Admin" asp-controller="Publishers" asp-action="Create"><button class="btn btn-primary waves-effect waves-light">افزودن <i class="fa fa-plus"></i></button></a>

                                </div>
                            </div>
                        </div>

                        <div class="editable-responsive">
                            <table class="table table-striped" id="datatable-editable">
                                <thead>
                                    <tr>
                                        <th>ایدی</th>
                                        <th>نام ناشر</th>
                                        <th>توضیحات</th>
                                        <th>فعالیت</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="gradeX">
                                            <td>@item.publisherID</td>
                                            <td>
                                                @item.publisherFullName
                                            </td>
                                            <td>@item.description</td>
                                            <td class="actions">
                                                <a href="#" class="hidden on-editing save-row"><i class="fa fa-save"></i></a>
                                                <a href="#" class="hidden on-editing cancel-row"><i class="fa fa-times"></i></a>
                                                <a href="/Admin/Publishers/Edit/@item.publisherID" class="on-default edit-row"><i class="fa fa-pencil"></i></a>
                                                <a href="/Admin/Publishers/Delete/@item.publisherID" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
                                            </td>
                                        </tr>
                                    }




                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end: panel body -->

                </div> <!-- end panel -->
            </div>














        </div>
        <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->