EbookPlatform/Areas/Admin/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Policy;

namespace EbookPlatform.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LanguageController : Controller
    {
        private readonly ILogger<LanguageController> _logger;
        private MyEbookPlatformContext _context;
        public LanguageController(ILogger<LanguageController> logger, MyEbookPlatformContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var languages = _context.languages.Where(c => c.isDeleted == false).ToList();
            return View(languages);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Language language)
        {
            if (!ModelState.IsValid)
            {
                return View(language);

            }
            if (languageDoesExist(language.languageTitle))
            {
                ModelState.AddModelError("languageTitle", "این زبان تکراری است!");
                return View(language);
            }

            _context.languages.Add(language);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var language = _context.languages.Find(id);
            language.isDeleted = true;
            _context.languages.Update(language);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            Language language = _context.languages.Find(id);

            if (language == null)
            {
                Response.StatusCode = 404;
                return View("UserNotFound");
            }

            return View(language);

        }


        [HttpPost]
        public IActionResult Edit(int id, Language language)
        {
            language.languageID = id;
            var languageFound = _context.languages.Find(id);
            languageFound.languageTitle = language.languageTitle;
            languageFound.languageDescription = language.languageDescription;

            _context.SaveChanges();


            return RedirectToAction(nameof(Index));
        }


        public bool languageDoesExist(string title)
        {
            if (_context.languages.Where(o => o.languageTitle == title).Count() > 0)
            {
                return true;
            }
            else
                return false;
        }


    }
}

EbookPlatform/Areas/Admin/Views/Language/Create.cshtml
@model EbookPlatform.Language

@{
    ViewData["Title"] = "AddLanguage";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 mt-4 p-3">
    <div class="card-box">



        <form method="post" asp-area="Admin" asp-controller="Language" asp-action="Create" style="margin-top:5%;">
            <div class="form-group">
                <label asp-for="languageTitle"></label>
                <input asp-for="languageTitle" type="text" parsley-trigger="change" placeholder=" " class="form-control" id="emailAddress" data-parsley-id="6">
                <span asp-validation-for="languageTitle" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="languageDescription"></label>
                <input type="text" class="form-control" asp-for="languageDescription">
                <span class="text-danger" asp-validation-for="languageDescription"></span>
            </div>

            <div class="form-group text-right m-b-0">
                <button class="btn btn-primary waves-effect waves-light" type="submit">
                    ثبت اطلاعات
                </button>
                <a asp-action="Index" class="btn btn-default waves-effect waves-light m-l-5">
                    لغو
                </a>
            </div>

        </form>
    </div>
</div>

EbookPlatform/Areas/Admin/Views/Language/Edit.cshtml
@model EbookPlatform.Language

@{
    ViewData["Title"] = "EditLanguage";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 mt-4 p-3">
    <div class="card-box">



        <form method="post" asp-area="Admin" asp-controller="Language" asp-action="Edit" style="margin-top:5%;">
            <div class="form-group">
                <label>عنوان زبان</label>
                <input type="text" class="form-control" name="languageTitle" value="@Model.languageTitle">
                <span class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>توضیحات</label>
                <input type="text" class="form-control" name="languageDescription" value="@Model.languageDescription">
                <span class="text-danger"></span>
            </div>

            <div class="form-group text-right m-b-0">
                <button class="btn btn-primary waves-effect waves-light" type="submit">
                    ثبت اطلاعات
                </button>
                <a asp-action="Index" class="btn btn-default waves-effect waves-light m-l-5">
                    لغو
                </a>
            </div>

        </form>
    </div>
</div>

EbookPlatform/Areas/Admin/Views/Language/Index.cshtml
@model IEnumerable<EbookPlatform.Language>

@{
    ViewData["Title"] = "Languages";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="content">
    <div class="container">


        <div class="row">

            <div class="col-sm-12">
                <div class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="m-b-30">
                                    <a asp-area="Admin" asp-controller="Language" asp-action="Create"><button class="btn btn-primary waves-effect waves-light">افزودن <i class="fa fa-plus"></i></button></a>

                                </div>
                            </div>
                        </div>

                        <div class="editable-responsive">
                            <table class="table table-striped" id="datatable-editable">
                                <thead>
                                    <tr>
                                        <th>ایدی</th>
                                        <th>نام ناشر</th>
                                        <th>توضیحات</th>
                                        <th>فعالیت</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="gradeX">
                                            <td>@item.languageID</td>
                                            <td>
                                                @item.languageTitle
                                            </td>
                                            <td>@item.languageDescription</td>
                                            <td class="actions">
                                                <a href="#" class="hidden on-editing save-row"><i class="fa fa-save"></i></a>
                                                <a href="#" class="hidden on-editing cancel-row"><i class="fa fa-times"></i></a>
                                                <a href="/Admin/Language/Edit/@item.languageID" class="on-default edit-row"><i class="fa fa-pencil"></i></a>
                                                <a href="/Admin/Language/Delete/@item.languageID" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
                                            </td>
                                        </tr>
                                    }




                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end: panel body -->

                </div> <!-- end panel -->
            </div>














        </div>
        <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->